spring:
  cloud:
    function:
      definition: shop-order;orderStock
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        shop-order-out-0:
          destination: SHOP_ORDER
        orderStock-in-0:
          destination: SHOP_ORDER_STOCK
        shop-order-check-stock-out-0:
          destination: SHOP_ORDER_CHECK_STOCK
server:
  port: 8087
