server:
  port: 8999
spring:
  cloud:
    gateway:
      routes:
#        - id: store-service
#          uri: http://localhost:8088
#          predicates:
#            - Path=/store/**
#  #          - Before=2017-09-11T17:42:47.789-07:00[America/Alaska]
#          filters:
#            - StripPrefix=1
##            - AddResponseHeader=X-CUSTOM-RESPONSE,HELLO
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1
