server:
  port: 8999
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/store/**
  #          - Before=2017-09-11T17:42:47.789-07:00[America/Alaska]
          filters:
            - StripPrefix=1
#            - AddResponseHeader=X-CUSTOM-RESPONSE,HELLO
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1
