spring:
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/ge-store
    username: postgres
    password: postgres
  application:
    name: store-service
server:
  port: 8083
feign:
  circuitbreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh
